"""create_prices_table

Revision ID: 0001
Revises: 
Create Date: 2026-05-04 11:59:28.460880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('value_mwh', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('value_kwh', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_datetime_provider', 'prices', ['datetime_utc', 'provider'], unique=True)
    op.create_index('idx_prices_datetime_utc', 'prices', ['datetime_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prices_datetime_utc', table_name='prices')
    op.drop_index('idx_prices_datetime_provider', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
